name: Generate Datas

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  # Generar ambos archivos (Serpiente y Estadísticas)
  generate-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Generar la serpiente directamente en la raíz
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jorgehdzriv
          svg_out_path: github-contribution-grid-snake.svg

      # 2. Generar las estadísticas directamente en la raíz
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg # Guardar directo en raíz
          config_timezone: America/Mexico_City
          plugin_languages: yes
          plugin_habits: yes
          plugin_achievements: yes

      # 3. Mover los archivos a la rama 'output'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: . # <--- Aquí le decimos que tome la raíz, no 'dist'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Actualizar últimos proyectos
  update-activity:
    name: Update Latest Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Actualizando últimos proyectos"